version: '3.2'

services:
   frontend-appvideos:
      build: .
      container_name: frontend-appvideos
      volumes:
        - ".:/app"
      ports:
        - "3001:3000"

networks:
   default:
      external: true
      name: appvideos