apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
         - name: frontend-container
           image: felippedeiro/frontend-appvideos:v2
           volumeMounts:
             - name: frontend-volume
               mountPath: /app/.env
               subPath: .env
           ports:
             - containerPort: 3000

      volumes:
        - name: frontend-volume
          configMap:
            name: frontend-configmap
            items:
              - key: env
                path: .env

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  env: |
     REACT_APP_BACKEND_URL=http://localhost:3001